### ISSUE TITLE
XamlAnimatedGif in DataGrid: No imaging component suitable to complete this operation was found.

### ISSUE THREAD

**Issue by Dunge** [XamlAnimatedGif/XamlAnimatedGif#84]
Hello Thomas, it's me again. I got another hard one for you.

I'm getting an exception thrown when I put the XamlAnimatedGif control in a DataGrid column template and use the SourceStream property as soon as I scroll down in the DataGrid.

I thought it was about the WPF panel virtualization feature causing problem, but I don't have any problem when they are in a listbox (also virtualized). I also don't have any problem when I use an URI instead of a Stream.

```
{"Exception from HRESULT: 0x88982F50"} No imaging component suitable to complete this operation was found.
   at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.EndInit()
   at XamlAnimatedGif.AnimationBehavior.<InitAnimationAsync>d__44.MoveNext()
```

The error stack seems to point in libraries internal to Microsoft. I also found on Google many instance of this HRESULT code, some are because the file is of an unsupported format, or corrupted. Others point out it might happen when a different thread than the UI thread is used to create the bitmaps.

Code to reproduce:
MainWindow.xaml.cs:
```
using System.Collections.ObjectModel;
using System.Globalization;
using System.IO;
using System.Threading;

namespace Gif
{
    public partial class MainWindow
    {
        public MainWindow()
        {
            DataContext = this;
            InitializeComponent();

            for (var i = 0; i < 10; i++)
//                ItemList.Add(new RowModel { Anim = new Uri(new FileInfo("animated.gif").FullName) });
                ItemList.Add(new RowModel { Anim = new FileStream("animated.gif", FileMode.Open, FileAccess.Read) });
        }

        private ObservableCollection<RowModel> _itemList = new ObservableCollection<RowModel>();
        public ObservableCollection<RowModel> ItemList
        {
            get { return _itemList; }
            set { _itemList = value; }
        }
    }

    public class RowModel
    {
//        public Uri Anim { get; set; }
        public Stream Anim { get; set; }
    }
}
```

MainWindow.xaml:
```
<Window x:Class="Gif.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:gif="https://github.com/XamlAnimatedGif/XamlAnimatedGif"
        Title="MainWindow" Height="350" Width="525">
    <Grid>
        <DataGrid ItemsSource="{Binding ItemList}"
                  AutoGenerateColumns="False">
            <DataGrid.Columns>
                <DataGridTemplateColumn Header="Animation">
                    <DataGridTemplateColumn.CellTemplate>
                        <DataTemplate>
                            <Image gif:AnimationBehavior.SourceStream="{Binding Anim}"
                                   gif:AnimationBehavior.RepeatBehavior="Forever" />
                        </DataTemplate>
                    </DataGridTemplateColumn.CellTemplate>
                </DataGridTemplateColumn>
            </DataGrid.Columns>
        </DataGrid>
    </Grid>
</Window>
```

You can change the two commented lines to use an URI instead of a stream (and rename SourceStream to SourceUri in the xaml) and it works fine.

I thought maybe the different file stream had problem accessing the file at the same time, so I tried to load multiple byte[] and creating different MemoryStream instead, but no I get the same problem.

I know this might be a bit complex to resolve, and might be a bug internal to Microsoft unrelated to your lib. But using normal Image controls with jpg in a DataGrid works fine. I'm stumped and don't know where else to look, so any insight from your part will be very appreciated.

Thanks again!

**Comment by thomaslevesque** [comment]
Hi @Dunge,

Thanks for the report.

According to the stack trace, it seems to be happening [here](https://github.com/XamlAnimatedGif/XamlAnimatedGif/blob/master/XamlAnimatedGif.Shared/AnimationBehavior.cs#L523), which means it has already failed to decode the stream as an animated GIF and is trying to fall back to decoding it as a simple non-animated image. But seeing this code again, there's an obvious bug: the stream is not rewinded, so it's not at the beginning and can't be used to decode the image... Also, the fallback decoding should be done in a try/catch, since it can fail.

This leaves the question of why it ended up in the `catch(InvalidSignatureException)` block in the first place... I'll try to investigate further when I find the time.

(I have a suspicion that the binding happens more than once... does the error still happen if you move `DataContext = this` to the end of the constructor?)

**Comment by Dunge** [comment]
> (I have a suspicion that the binding happens more than once... does the error still happen if you move DataContext = this to the end of the constructor?)

Yes it does, the error occurs when using the scrollbar of the DataGrid, but the first opening of the Window the first view works fine. You are probably right that the binding happens multiple time, but that's a behavior internal to the DataGrid control for optimization, not in my sample code.

Thanks for the investigation, I admit I hadn't even tried to load your source code to see where the problem occurs. I just did, and yes, adding a stream.Seek(0, SeekOrigin.Begin); in the InvalidSignatureException catch block remove the error, but nothing get displayed.

I put a breakpoint at the place the InvalidSignatureException is thrown, and yes it works the fine time, and then it comes back and the stream cursor instead of being at position 3 after reading 'GIF', is at position 9014. Like the previous issue, probably two threads or two bindings trying to read the same stream simultaneously.

I'm having a hard time trying to debug with async calls. When the error happens, I can return up the stack to the InitAnimationAsync method, but I'm unable to see what's calling it. When I put a breakpoint there, I can see it's often called from the Image_Loaded event, but then it don't crash.

**Comment by thomaslevesque** [comment]
OK, I reproduced the issue, and I think I know what the problem is: it's because the same stream is bound to a different `Image` control. Each `Image` has its own `Animator`, which seeks and reads the stream independently.

Actually, I'm not even sure this should be considered a bug; there's no way to make it work with multiple images bound to the same stream, for the same reason you can't use a stream from multiple threads.

In your case, disabling virtualization fixes the issue, but I realize it's not ideal... Another approach that would work would be to return a fresh stream every time the `Anim` property is invoked; this would ensure each stream is used only once.

**Comment by Dunge** [comment]
Quote from my original post:

> I thought maybe the different file stream had problem accessing the file at the same time, so I tried to load multiple byte[] and creating different MemoryStream instead, but no I get the same problem.

Haven't tried debugging to see if it crash exactly the same way, but I'm sure it's not working.

**Comment by thomaslevesque** [comment]
@Dunge I think you misunderstood what I was suggesting. With the approach you describe, it's still possible for multiple `Image` controls to be bound to the same `RowModel`, and thus to the same stream. What I was saying is that the `Anim` property could return a new stream every time it's called.

However, I just tried it, and I still get the same error, so maybe my theory was wrong... I really don't know what's going on 😕

**Comment by thomaslevesque** [comment]
There's been no activity in this issue for some time, so I'm closing it.
We can reopen the issue in the future should sufficient interest arise.
